export const VALUES_LOADING = 'VALUES_LOADING';
export const VALUES_FAILED = 'VALUES_FAILED';
export const ADD_VALUES = 'ADD_VALUES';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
// export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
// export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';
export const ADD_USER = 'ADD_USER';

export const SET_USER_MAIN_PHOTO_URL = 'SET_USER_MAIN_PHOTO_URL';

// export const UPLOAD_FILE = 'UPLOAD_FILE';